version: '2'

services:
    tsdb:
        image: petergrace/opentsdb-docker
        volumes:
            - ./data/hbase:/data/hbase
        expose:
            - "16010"
            - "4242"
            - "60000"
            - "60010"
            - "60030"
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        volumes:
            - ./data/grafana/:/var/lib/grafana
        depends_on:
            - "tsdb"
    sampler:
        build: sampler
        depends_on:
            - "tsdb"

networks:
    default:
        driver: bridge

